<div class="clearfix" id="ads">
	<div class="visible-xs hidden-sm hidden-md hidden-lg col-xs-12">
		<div class="center-block" style="width:100%; max-width:320px; height:50px;">
			<a href="http://www.lexusofaustin.com" target="_blank"><img src="assets/Lexus_SXSW_320x50_CMGAE0000030907-005.jpg"></a>
		</div>
	</div>
	<div class="hidden-xs visible-sm visible-md visible-lg col-xs-12">
		<div class="center-block" style='width:100%; max-width:728px; height:90px;'>
			<a href="http://www.lexusofaustin.com" target="_blank"><img src="assets/Lexus_SXSW_728x90_CMGAE0000030907-004.jpg"></a>
		</div>
	</div>
</div>
